version: '3'

services:
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
    networks:
      - nextcloud
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - nextcloud
  app:
    container_name: nextcloud-app
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_HOST=database
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=pass
    depends_on:
      - database
      - redis
    networks:
      - nextcloud

  web:
    build: ./web
    restart: always
    ports:
      - 80:80
    links:
      - app
    volumes:
      - nextcloud:/var/www/html:ro
    volumes_from:
      - app
    networks:
      - nextcloud

volumes:
  database:
  nextcloud:

networks:
  nextcloud: