name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Init Onlyoffice enviroment
      run: chmod +x ./init_onlyoffice.sh
      
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
